language: go

services:
  - docker

go_import_path: github.com/awslabs/aws-lambda-container-image-converter

go:
    - 1.13.x

script:
    - make install-tools
    - make
    - make integration-test
    - make stage-release-binaries
    - make clean
    - make docker-build
    - make docker-test
    - make clean
    - docker build -t img2lambda .
