service: php-example-hello

provider:
  name: aws
  runtime: provided

functions:
  hello:
    handler: hello.hello
    package:
      artifact: ../output/function.zip
    layers:
      ${file(../output/layers.json)}
  goodbye:
    handler: goodbye.goodbye
    package:
      artifact: ../output/function.zip
    layers:
      ${file(../output/layers.json)}
