
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.16"

[[constraint]]
  name = "github.com/containers/image"
  version = "1.3.0"

[[constraint]]
  name = "github.com/mattn/go-zglob"
  version = "0.0.1"

[[constraint]]
  name = "github.com/mholt/archiver"
  version = "3.1.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[override]]
  name = "github.com/docker/docker"
  revision = "6e3113f700dea1bf2785d94731b4b5a1e602d9ab"

[[override]]
  name = "github.com/docker/distribution"
  revision = "83389a148052d74ac602f5f1d62f86ff2f3c4aa5"
